#!/usr/bin/env node
// Renders the Cleaniche logo animation with headless Chromium (Playwright) and encodes with ffmpeg.
//
//   node tools/render.js                       # both formats → out/*.mp4 (with audio if out/sound.wav exists)
//   node tools/render.js --size 1080x1350      # one format
//   node tools/render.js --stills 1,2.5,9.9    # PNG stills only → out/stills/
//   node tools/render.js --fps 24
//
// Requires: playwright (global install is fine — run with NODE_PATH=$(npm root -g)), ffmpeg on PATH.

const fs = require('fs');
const path = require('path');
const http = require('http');
const { spawn } = require('child_process');
const { chromium } = require('playwright');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'out');
const args = process.argv.slice(2);
const opt = (name, def) => { const i = args.indexOf('--' + name); return i >= 0 ? args[i + 1] : def; };
const FPS = Number(opt('fps', 30));
const SIZES = opt('size', '3840x2160,2160x2700,1920x1080,1080x1350').split(',');
const STILLS = opt('stills', null);
const DURATION = 10;

// 1. Data: the supplied logo paths, verbatim, plus the symbol's centreline routes.
function buildData() {
  const svg = fs.readFileSync(path.join(ROOT, 'assets/cleaniche-logo-outlined.svg'), 'utf8');
  const ds = [...svg.matchAll(/<path class="cls-1" d="([^"]+)"/g)].map(m => m[1]);
  if (ds.length < 2) throw new Error('logo SVG: expected symbol + wordmark paths');
  const data = { logo: { symbol: ds[0], wordmark: ds.slice(1) }, routes: JSON.parse(fs.readFileSync(path.join(ROOT, 'src/routes.json'), 'utf8')) };
  fs.writeFileSync(path.join(ROOT, 'src/data.js'),
    '// Generated by tools/render.js from assets/cleaniche-logo-outlined.svg and src/routes.json — do not edit.\n' +
    'window.CLEANICHE_DATA = ' + JSON.stringify(data) + ';\n');
}

function serve() {
  const types = { '.html': 'text/html', '.js': 'text/javascript', '.json': 'application/json', '.woff2': 'font/woff2', '.svg': 'image/svg+xml' };
  const srv = http.createServer((req, res) => {
    const p = path.join(ROOT, decodeURIComponent(new URL(req.url, 'http://x').pathname));
    if (!p.startsWith(ROOT) || !fs.existsSync(p) || fs.statSync(p).isDirectory()) { res.writeHead(404); return res.end(); }
    res.writeHead(200, { 'content-type': types[path.extname(p)] || 'application/octet-stream' });
    fs.createReadStream(p).pipe(res);
  });
  return new Promise(r => srv.listen(0, '127.0.0.1', () => r(srv)));
}

async function grab(page, t) {
  const b64 = await page.evaluate(t => { window.renderFrame(t); return document.getElementById('c').toDataURL('image/png').split(',')[1]; }, t);
  return Buffer.from(b64, 'base64');
}

async function renderSize(browser, port, size) {
  const [w, h] = size.split('x').map(Number);
  const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
  page.on('pageerror', e => { console.error('page error:', e); process.exit(1); });
  await page.goto(`http://127.0.0.1:${port}/src/index.html?render&size=${size}`);
  await page.evaluate(() => window.ready);

  if (STILLS) {
    const dir = path.join(OUT, 'stills'); fs.mkdirSync(dir, { recursive: true });
    for (const t of STILLS.split(',').map(Number)) {
      const f = path.join(dir, `${size}_${t.toFixed(2)}s.png`);
      fs.writeFileSync(f, await grab(page, t)); console.log(f);
    }
    return page.close();
  }

  const name = `cleaniche-logo-animation-${size}`;
  const wav = path.join(OUT, 'sound.wav');
  const ff = ['-y', '-loglevel', 'error', '-f', 'image2pipe', '-framerate', String(FPS), '-c:v', 'png', '-i', '-'];
  if (fs.existsSync(wav)) ff.push('-i', wav, '-c:a', 'aac', '-b:a', '256k', '-shortest');
  ff.push('-c:v', 'libx264', '-preset', w * h > 4e6 ? 'medium' : 'slow', '-crf', w * h > 4e6 ? '16' : '14', '-pix_fmt', 'yuv420p', '-profile:v', 'high',
    '-color_primaries', 'bt709', '-color_trc', 'bt709', '-colorspace', 'bt709', '-movflags', '+faststart',
    '-r', String(FPS), path.join(OUT, name + '.mp4'));
  const enc = spawn('ffmpeg', ff, { stdio: ['pipe', 'inherit', 'inherit'] });
  const done = new Promise((res, rej) => enc.on('close', c => (c ? rej(new Error('ffmpeg exit ' + c)) : res())));
  const n = Math.round(DURATION * FPS);
  for (let i = 0; i < n; i++) {
    const png = await grab(page, i / FPS);
    if (!enc.stdin.write(png)) await new Promise(r => enc.stdin.once('drain', r));
    if (i % 30 === 0) process.stdout.write(`\r${size}: frame ${i}/${n}`);
  }
  enc.stdin.end(); await done;
  // poster: the final lockup
  fs.writeFileSync(path.join(OUT, name + '-final-frame.png'), await grab(page, DURATION - 1 / FPS));
  console.log(`\r${size}: done → out/${name}.mp4`);
  await page.close();
}

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  buildData();
  const srv = await serve();
  const browser = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
  try { for (const s of SIZES) await renderSize(browser, srv.address().port, s); }
  finally { await browser.close(); srv.close(); }
})().catch(e => { console.error(e); process.exit(1); });
